services:
  traefik:
    image: traefik:3.2.2
    container_name: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pilo
    logging:
      driver: loki
      options:
        loki-url: http://10.5.0.99:3100/loki/api/v1/push
        loki-retries: 5

  piloapi:
    image: piloapi
    build:
      context: ./app/pilo-api
      dockerfile: ./Dockerfile
    container_name: piloapi
    labels:
      - "traefik.http.routers.piloapi.rule=PathPrefix(`/weatherforecast`)"
      - "traefik.http.services.piloapi.loadbalancer.server.port=8080"
    networks:
      - pilo
    logging:
      driver: loki
      options:
        loki-url: http://10.5.0.99:3100/loki/api/v1/push
        loki-retries: 5

  piloweb:
    image: piloweb
    build:
      context: ./app/pilo-app
      dockerfile: ./Dockerfile
    container_name: piloweb
    labels:
      - "traefik.http.routers.piloweb.rule=PathPrefix(`/`)"
      - "traefik.http.services.piloweb.loadbalancer.server.port=80"
    networks:
      - pilo
    logging:
      driver: loki
      options:
        loki-url: http://10.5.0.99:3100/loki/api/v1/push
        loki-retries: 5

  ###################
  ## Observability ##
  ###################

  loki:
    image: grafana/loki:3.3.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      pilo:
        ipv4_address: 10.5.0.99

  grafana:
    image: grafana/grafana-oss:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./docker-compose-configs/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./docker-compose-configs/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - pilo

###################
## Network Setup ##
###################
networks:
  pilo:
    driver: bridge
    name: pilo
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
