apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-app
  type: ClusterIP
