grafana:
  grafana.ini:
    server:
      domain: ${K3S_VM_FQDN}
      root_url: https://${K3S_VM_FQDN}/grafana/
      serve_from_sub_path: true
  ingress:
    enabled: true
    hosts:
      - ${K3S_VM_FQDN}
    path: "/grafana"

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki-gateway.monitoring.svc.cluster.local
          isDefault: true
          jsonData:
            maxLines: 1000
