grafana:
  grafana.ini:
    server:
      domain: ${K3S_VM_FQDN}
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: true
    hosts:
      - "${K3S_VM_FQDN}"
    path: "/grafana"

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.monitoring.svc.cluster.local
          isDefault: true
          jsonData:
            maxLines: 1000
